import React from "react";

interface SoapNoteDisplayProps {
  soapNote: string;
}

export const SoapNoteDisplay: React.FC<SoapNoteDisplayProps> = ({
  soapNote,
}) => {
  if (!soapNote) return null;

  const formatSoapNote = (note: string) => {
    return note.split("\n").map((line, index) => (
      <div
        key={index}
        className={
          line.includes(":") && line.length < 50
            ? "soap-header"
            : "soap-content"
        }
      >
        {line}
      </div>
    ));
  };

  return (
    <div className="soap-section">
      <h2>SOAP Note (Generated by Google Gemini)</h2>
      <div className="soap-content">{formatSoapNote(soapNote)}</div>
    </div>
  );
};
